### ISSUE TITLE
Minor doc change

### ISSUE THREAD

**Issue by jleaders** [duncan3dc/sessions#3]
Just a minor note: you may want to add the array set to the readme.md -- it's a really useful feature to set multiple session variables at once and it was one of the main reasons I picked your library, but I had to dig through your docs to find out if that feature existed :)

**Comment by duncan3dc** [comment]
Hi Jonathan, thanks for your interest in the library, I'm glad you've found it useful.

I prefer READMEs that are short and just contain the absolute basics with links to further reading. I actually think there's a couple of examples too many in the current README! :laughing: 

I'll take a look at modifying the README to see if I can squeeze in a multi-set example though :+1:
