### ISSUE TITLE
Error if used when session is already active

### ISSUE THREAD

**Issue by GDIBass** [duncan3dc/sessions#5]
Hello, we're currently getting an error when trying to check values if the session is already active:

FastCGI sent in stderr: "PHP message: PHP Warning:  session_cache_limiter(): Cannot change cache limiter when session is active in /home/vagrant/code/SPI/vendor/duncan3dc/sessions/src/SessionInstance.php on line 66

I'll have a PR for this open shortly.

**Comment by duncan3dc** [comment]
Hi Matt, do you have a short script to reproduce the issue?

**Comment by duncan3dc** [comment]
I'm not sure if it makes sense to use this library alongside another session management library, there's likely to be many more issues than just one.

Could you explain more about your use case? Are you intentionally running two session libraries, or is it out of your control?

**Comment by jleaders** [comment]
I ran into this, but it turned out I had been accidentally calling session_start() and/or having whitespace emitted in a file, so I got around it just fine.

**Comment by duncan3dc** [comment]
Thanks, we'll handle this on the pull request from here :+1:
